name: Build_Workflow

on:
  push:
    branches: [ main ]
    paths: [ src ]
  pull_request:
    branches: [ main ]
    paths: [ src ]
  workflow_dispatch:

jobs:
  prep:
    env:
      ACTION_IS_NULL: ${{ github.event.action == null }}
      ACTION: ${{ github.event.action }}
    runs-on: ubuntu-latest
    steps:
      - name: Prep 
        run: |
          echo "Event: $ACTION ($ACTION_IS_NULL)"
        
  build:
    env:
      ACTION_IS_NULL: ${{ github.event.action == null }}
      ACTION: ${{ github.event.action }}
      root: ${{ github.workspace }}
      artifacts: '${{ github.workspace }}/artifacts'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        if: ${{ github.event.action == 'push'}}
        run: cd ${root}; pwsh ${root}/.github/workflows/bootstrap.ps1

      - name: Upload Powershell Artifact
        if: ${{ github.event.action == 'push'}}
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Workflow-Artifacts-PS
          path: '${{ github.workspace }}/artifacts/powershell.zip'
          if-no-files-found: warn
          retention-days: 90
          
      - name: Upload Console Artifact
        if: ${{ github.event.action == 'push'}}
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Workflow-Artifacts-Console
          path: '${{ github.workspace }}/artifacts/workflow.zip'
          if-no-files-found: warn
          retention-days: 90

  PullTop100:
    env:
      ACTION_IS_NULL: ${{ github.event.action == null }}
      ACTION: ${{ github.event.action }}
      root: ${{ github.workspace }}
      artifacts: '${{ github.workspace }}/artifacts'

    if: ${{ github.event.action == null}}
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
#         with:
#           name: Workflow-Artifacts-Console
#           path: ${{ github.workspace }}

      # Runs a set of commands using the runners shell
      - name: Pull Top 100
        run: |
          unzip workflow.zip
          ls -al
          
