name: Build_Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cd ${root}; pwsh ${root}/.github/workflows/bootstrap.ps1
        env:
         root: ${{ github.workspace }}
         
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Workflow-Artifacts
          path:  ${{ github.workspace }}/artifacs/**/*
          if-no-files-found: warn
          retention-days: 90
