name: Build_Workflow

on:
  push:
    branches: [ main ]
    paths: [ src ]
  pull_request:
    branches: [ main ]
    paths: [ src ]
  workflow_dispatch:

jobs:
  prep:
    env:
      action: '${{ github.event.action }}'
    runs-on: ubuntu-latest
    steps:
      - name: Prep 
        run: |
          echo 'Event: ${action}'
        
  build:
    if: ${{ github.event.action == 'push'}}
    runs-on: ubuntu-latest
    env:
     root: ${{ github.workspace }}
     artifacts: '${{ github.workspace }}/artifacts'

    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        run: cd ${root}; pwsh ${root}/.github/workflows/bootstrap.ps1

      - run: ls -al ${artifacts}

      - name: Upload Powershell Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Workflow-Artifacts-PS
          path: '${{ github.workspace }}/artifacts/powershell.zip'
          if-no-files-found: warn
          retention-days: 90
          
      - name: Upload Console Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Workflow-Artifacts-Console
          path: '${{ github.workspace }}/artifacts/workflow.zip'
          if-no-files-found: warn
          retention-days: 90

  PullTop100:
    if: ${{ github.event.action == ''}}
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
#         with:
#           name: Workflow-Artifacts-Console
#           path: ${{ github.workspace }}

      # Runs a set of commands using the runners shell
      - name: Pull Top 100
        run: |
          unzip workflow.zip
          ls -al
          
