name: Build_Workflow

on:
  push:
    branches: [ main ]
    paths: [ 'src/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'src/**' ]
  workflow_dispatch:

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - name: Prep 
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Event: ${{ github.event.action }}"
          echo "Event: ${{ github.event }}"
          echo "Event: ${{ github }}"
        
  build:
    env:
      root: ${{ github.workspace }}
      artifacts: '${{ github.workspace }}/artifacts'
      github_token: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        if: github.event_name == 'push'
        run: |
          cd ${root}; 
          pwsh ${root}/.github/workflows/bootstrap.ps1
          cd ${root}/artifacts
          git add *.zip
          git commit -m 'Build Artifacts'
          git push https://sharpninja:${github_token}@github.com/NugetCodeReview/Workflow.git

#       - name: Upload Powershell Artifact
#         if: github.event_name == 'push'
#         uses: actions/upload-artifact@v3.0.0
#         with:
#           name: Workflow-Artifacts-PS
#           path: '${{ github.workspace }}/artifacts/powershell.zip'
#           if-no-files-found: warn
#           retention-days: 90
          
#       - name: Upload Console Artifact
#         if: github.event_name == 'push'
#         uses: actions/upload-artifact@v3.0.0
#         with:
#           name: Workflow-Artifacts-Console
#           path: '${{ github.workspace }}/artifacts/workflow.zip'
#           if-no-files-found: warn
#           retention-days: 90

  PullTop100:
    env:
      root: ${{ github.workspace }}
      artifacts: '${{ github.workspace }}/artifacts'

    if: github.event_name != 'push'
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
#         with:
#           name: Workflow-Artifacts-Console
#           path: ${{ github.workspace }}

      # Runs a set of commands using the runners shell
      - name: Pull Top 100
        run: |
          unzip workflow.zip
          ls -al
          
