name: Build_Workflow

on:
  push:
    branches: [ main ]
    paths: [ 'src/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'src/**' ]
  workflow_dispatch:

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - name: Prep 
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Event: ${{ github.event.action }}"
          echo "Event: ${{ github.event }}"
          echo "Event: ${{ github }}"
        
  build:
    env:
      root: ${{ github.workspace }}
      artifacts: '${{ github.workspace }}/artifacts'
      github_token: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        if: github.event_name == 'push'
        run: |
          cd ${root}; 
          pwsh ${root}/.github/workflows/bootstrap.ps1
          cd ${artifacts}
          git config user.email "ninja@thesharp.ninja"
          git config user.name "GitHub Action"
          git add *.zip -f
          git commit -m 'Build Artifacts'
          git push https://sharpninja:${github_token}@github.com/NugetCodeReview/Workflow.git

  PullTop100:
    env:
      root: ${{ github.workspace }}
      artifacts: '${{ github.workspace }}/artifacts'

    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Runs a set of commands using the runners shell
      - name: Pull Top 100
        run: |
          cd ${artifacts}
          unzip workflow.zip
          ls -al
          workflow ForkTop100 AddWorkflowTop100
